"""

------------------------------------------------- Link for the challenge: https://codeforces.com/problemset/problem/2093/C ---------------------------------------

Pasha loves prime numbers∗! Once again, in his attempts to find a new way to generate prime numbers, he became interested in an algorithm he found on the internet:

To obtain a new number y, repeat k times the decimal representation of the number x (without leading zeros).
For example, for x=52 and k=3, we get y=525252, and for x=6 and k=7, we get y=6666666.

Pasha really wants the resulting number y to be prime, but he doesn't yet know how to check the primality of numbers generated by this algorithm. Help Pasha and tell him whether y is prime!

∗ An integer x is considered prime if it has exactly 2 distinct divisors: 1 and x. 
For example, 13 is prime because it has only 2 divisors: 1 and 13. 
Note that the number 1 is not prime, as it has only one divisor.

Input
Each test consists of several sets of input data. The first line contains a single integer t (1 ≤ t ≤ 100) — the number of sets of input data. The following lines describe the sets of input data.

The first and only line of each data set contains two integers: x and k (1 ≤ x ≤ 10^9, 1≤k≤7).

Output
For each set of input data, output «YES» (without quotes) if the resulting number y will be prime, and «NO» otherwise.

You may output «Yes» and «No» in any case (for example, the strings «yES», «yes», and «Yes» will be recognized as positive answers).

Input:
4
52 3
6 7
7 1
1 7

Output:
NO
NO
YES
NO
"""
def is_prime(n: int) -> bool:
    if n <= 1:
        return False
    if n <= 3:
        return True  # 2 and 3 are prime
    if n % 2 == 0 or n % 3 == 0:
        return False  # Exclude multiples of 2 and 3
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
        
    return True
cases = int(input())
for _ in range(cases):
    x, k = map(int, input().split())
    is_prime_x = is_prime(x)
    if(x == 1 and k == 2):
        print("YES")
    elif(is_prime_x and k == 1):
        print("YES")
    else:
        print("NO")